-- BoardGPT — Postgres schema (blueprint §4 PostgreSQL 15, §11 data model)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS games (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   TEXT,                 -- id generated by the extension (idempotency)
  user_id     TEXT NOT NULL DEFAULT 'demo',
  pgn         TEXT NOT NULL,
  result      TEXT NOT NULL DEFAULT '*',
  source      TEXT NOT NULL DEFAULT 'chess.com',
  analysis    JSONB,                -- cached post-game review
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS games_client_id_idx ON games (client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS games_user_idx ON games (user_id, created_at DESC);
